# python piaic assignment 

## implentation of any 50 numpy methods or attribute codes in jupyter notebook

In [1]:
import numpy as np

In [6]:
np.__version__

'1.19.2'

In [ ]:
# arr=np.array([1,2,3,4,5,6,7,10])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [9]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[arr % 2 == 1] = -1

In [19]:
arr

array([-1,  8,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr = np.arange(10)
new_arr=np.where(arr%2==1,-1,arr)
new_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [45]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [47]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [56]:
ad = np.array([2, 6, 1, 9, 10, 3, 27])
ad[np.where((ad>5)&(ad<11))]

array([ 6,  9, 10])

In [59]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [61]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [62]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [63]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.423, 0.023, 0.914],
       [0.226, 0.767, 0.389],
       [0.557, 0.454, 0.035],
       [0.092, 0.125, 0.932]])

In [66]:
np.set_printoptions(suppress=False)
np.random.seed(100)

rand_arr

array([[0.423, 0.023, 0.914],
       [0.226, 0.767, 0.389],
       [0.557, 0.454, 0.035],
       [0.092, 0.125, 0.932],
       [0.409, 0.451, 0.67 ]])

In [67]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a


array([ 0,  1,  2, ..., 12, 13, 14])

In [68]:
#logspace array
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)

[1.000e+35 7.743e+38 5.995e+42 ... 1.668e+62 1.292e+66 1.000e+70]


In [72]:
arr1 = np.array([[10, 20, 30], [40, 50, 60]])
arr2 = np.array([[2, 3, 4], [4, 6, 8]])
arr3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
print(np.add(arr1, arr2))

[[12 23 34]
 [44 56 68]]


TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'NoneType'